### ISSUE TITLE
Flex direction row-reverse not working?

### ISSUE THREAD

**Issue by alvarotrigo** [lyfeyaj/swipe#153]
As long as I add the row-reverse property the slider stops working:

```css
.swipe-wrap{
    display: flex;
    flex-direction: row-reverse;
}
``` 

Reproduction online:
https://jsfiddle.net/1t8b5746/2/

Not quite sure if there's a solution for it?
My use case is the following:

The elements on the mobile view should be displayed in a different order as in the desktop view.
I'm using swiper for the mobile view.
